server {
    listen 80;
    location / {
        proxy_pass       http://latex-pdf-web:5000;
        proxy_set_header Host $host;
        proxy_read_timeout 120s;
        proxy_buffering  off;
    }
}
